### PR TITLE
General python model format

### LINKED ISSUE #497: Add an example which deploys a regression model [.5]
Add an example to the examples directory (github.com/cortexlabs/cortex/tree/master/examples); like the others, it should have a README which links to a Colab that trains or exports the model, and a tutorial for how to use Cortex to deploy the model.

### LINKED ISSUE #506: Serve PyTorch models without requiring an ONNX export [3]
### Description

Serve PyTorch models without requiring an ONNX export.

### Motivation

Avoid the risk of unsupported PyTorch operations in ONNX.

### LINKED ISSUE #507: Deploy GPT-2 Hugging Face [1.5]
### Description

Add more examples of how to use Cortex to deploy state of the art models.

### Motivation

Ensure we support a variety of use cases.

### Additional Context

https://github.com/huggingface/transformers

### LINKED ISSUE #522: Support arbitrary metadata passthrough (API config -> handlers)
### Questions

* How does it affect the Python handler APIs?
* Should it be included as an optional argument to all handlers? Or should we pass in `api_config` to all handlers?
* Should tags be removed?

### Notes

* The code for this exists in git history

### PR DESCRIPTION
**Pull request by vishalbollu**
Closes #506, Closes #507, Closes #522, Closes #497 

---
Checklist:
- [ ] Run `make test` and `make lint`
- [ ] Test end to end manually (e.g. build/push all images, restart operator, and run `cx refresh`)
- [ ] Update examples
- [ ] Update documentation (add any new files to `summary.md`)
- [ ] Merge to master
- [ ] Cherry-pick into release branches if it's a bugfix
- [ ] Check [gitbook](https://www.cortex.dev/v/master/) that docs look good and links function properly
- [ ] Alert team if dev environment changed
- [ ] Delete the branch once it's merged

### CODE REVIEW

File: dev/registry.sh [hunk 1]
```diff
@@ -139,10 +141,12 @@ elif [ "$cmd" = "update" ]; then
     build_and_push $ROOT/images/istio-galley istio-galley latest
   fi
 
+  build_and_push $ROOT/images/downloader downloader latest
```
Comment (deliahu) [inline dev/registry.sh]: nit: if there was no particular reason to move downloader up here, do you mind moving it back down (just to clean up the diff)

File: README.md [hunk 2]
```diff
@@ -30,8 +30,9 @@ Define a `deployment` and an `api` resource. A `deployment` specifies a set of A
 
 - kind: api
   name: generator
-  model: s3://cortex-examples/text-generator/gpt-2/124M
```
Comment (deliahu) [inline README.md]: We should discuss, but we might want to leave the README as is until we release v0.10

File: examples/iris-pytorch/cortex.yaml [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+  name: iris
+  python_root: src/
+
+- kind: api
+  name: classifier
+  python:
+    inference: src/handler.py
+  metadata:
+    region: "us-west-2"
+    bucket: "data-vishal"
```
Comment (deliahu) [inline examples/iris-pytorch/cortex.yaml]: Will this be moved to cortex-examples?

File: examples/iris-pytorch/cortex.yaml [hunk 4]
```diff
@@ -0,0 +1,12 @@
+- kind: deployment
+  name: iris
+  python_root: src/
+
+- kind: api
+  name: classifier
+  python:
+    inference: src/handler.py
+  metadata:
+    region: "us-west-2"
```
Comment (deliahu) [inline examples/iris-pytorch/cortex.yaml]: Is this necessary? If so, maybe:

```yaml
metadata:
    bucket_name: <>
    bucket_region: <>
    model_path: <>
```

File: examples/iris-pytorch/sample.json [hunk 5]
```diff
@@ -0,0 +1,6 @@
+{
+    "sepal_length": 2.2,
+    "sepal_width": 3.6,
+    "petal_length": 1.4,
+    "petal_width": 3.3
+}
```
Comment (deliahu) [inline examples/iris-pytorch/sample.json]: nit: trailing new line

File: examples/iris-pytorch/src/model.py [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+        if epoch % 100 == 0:
+            print("number of epoch {} loss {}".format(epoch, loss))
+
+    predict_out = model(test_X)
+    _, predict_y = torch.max(predict_out, 1)
+
+    print("prediction accuracy {}".format(accuracy_score(test_y.data, predict_y.data)))
+
+    placeholder = torch.randn(1, 4)
+    torch.onnx.export(
```
Comment (deliahu) [inline examples/iris-pytorch/src/model.py]: This is not necessary now. Is the code that saves `iris_model.pth` in this file?

File: examples/pytorch-gpt2/cortex.yaml [hunk 7]
```diff
@@ -0,0 +1,9 @@
+- kind: deployment
+  name: gpt2
+
+- kind: api
+  name: text-gen
+  python:
+    inference: inference.py
+  metadata:
+    word_length: 20
```
Comment (deliahu) [inline examples/pytorch-gpt2/cortex.yaml]: nit: trailing new line

Comment (deliahu) [inline examples/pytorch-gpt2/cortex.yaml]: nit: `num_words` might be more descriptive

File: examples/pytorch-gpt2/inference.py [hunk 8]
```diff
@@ -0,0 +1,95 @@
...
+            filtered_logits = top_k_top_p_filtering(next_token_logits, top_k=top_k, top_p=top_p)
+            if temperature == 0:  # greedy sampling:
+                next_token = torch.argmax(filtered_logits).unsqueeze(0)
+            else:
+                next_token = torch.multinomial(F.softmax(filtered_logits, dim=-1), num_samples=1)
+            generated = torch.cat((generated, next_token.unsqueeze(0)), dim=1)
+    return generated
+
+
+model = GPT2LMHeadModel.from_pretrained("distilgpt2")
```
Comment (deliahu) [inline examples/pytorch-gpt2/inference.py]: How do you feel about lines 81-86 moving to the top?

File: examples/pytorch-gpt2/inference.py [hunk 9]
```diff
@@ -0,0 +1,95 @@
...
+import numpy as np
+import argparse
+import logging
+from tqdm import trange
+import torch.nn.functional as F
+import torch
+from transformers import GPT2Tokenizer, GPT2LMHeadModel
+
+
+def top_k_top_p_filtering(logits, top_k=0, top_p=0.0, filter_value=-float("Inf")):
```
Comment (deliahu) [inline examples/pytorch-gpt2/inference.py]: Maybe we should link the source of this code?

File: examples/pytorch-gpt2/sample.json [hunk 10]
```diff
@@ -0,0 +1,3 @@
+{
+    "text": "machine learning"
+}
```
Comment (deliahu) [inline examples/pytorch-gpt2/sample.json]: nit: new line

File: examples/pytorch-imagenet/inference.py [hunk 11]
```diff
@@ -0,0 +1,40 @@
+import requests
+import base64
+from PIL import Image
+from io import BytesIO
+from torchvision import transforms
+import torchvision
+import torch
+
+labels = requests.get(
```
Comment (deliahu) [inline examples/pytorch-imagenet/inference.py]: Do you think some of this should go in `init()`?

File: examples/pytorch-gpt2/inference.py (hunk 8 above)
Comment (deliahu) [inline examples/pytorch-gpt2/inference.py]: Do you think this line and the one below should go in `init()`?

File: examples/pytorch-imagenet/sample.json [hunk 12]
```diff
@@ -0,0 +1,3 @@
+{
+    "url": "https://bowwowinsurance.com.au/wp-content/uploads/2018/10/akita-700x700.jpg"
+}
```
Comment (deliahu) [inline examples/pytorch-imagenet/sample.json]: nit: new line

File: pkg/operator/api/userconfig/errors.go [hunk 13]
```diff
@@ -180,14 +178,18 @@ func ErrorSpecifyAllOrNone(vals ...string) error {
 	}
 }
 
-func ErrorSpecifyOnlyOne(vals ...string) error {
-	message := fmt.Sprintf("please specify exactly one of %s", s.UserStrsOr(vals))
-	if len(vals) == 2 {
-		message = fmt.Sprintf("please specify either %s or %s, but not both", s.UserStr(vals[0]), s.UserStr(vals[1]))
+func ErrorSpecifyOne(vals ...string) error {
```
Comment (deliahu) [inline pkg/operator/api/userconfig/errors.go]: nit: maybe this should be called `ErrorSpecifyOneModelFormatFoundNone`

File: pkg/operator/api/userconfig/errors.go [hunk 14]
```diff
@@ -180,14 +178,18 @@ func ErrorSpecifyAllOrNone(vals ...string) error {
...
+	message := fmt.Sprintf("please specify one model format (%s)", s.UserStrsOr(vals))
+	return Error{
+		Kind:    ErrSpecifyOnlyOne,
+		message: message,
 	}
+}
 
+func ErrorFoundMultipleSpecifyOnlyOneModelFormat(found []string, vals ...string) error {
```
Comment (deliahu) [inline pkg/operator/api/userconfig/errors.go]: nit: maybe this should be called `ErrorSpecifyOneModelFormatFoundMultiple`

File: pkg/operator/api/userconfig/errors.go [hunk 15]
```diff
@@ -180,14 +178,18 @@ func ErrorSpecifyAllOrNone(vals ...string) error {
 	}
 }
 
-func ErrorSpecifyOnlyOne(vals ...string) error {
-	message := fmt.Sprintf("please specify exactly one of %s", s.UserStrsOr(vals))
-	if len(vals) == 2 {
-		message = fmt.Sprintf("please specify either %s or %s, but not both", s.UserStr(vals[0]), s.UserStr(vals[1]))
+func ErrorSpecifyOne(vals ...string) error {
+	message := fmt.Sprintf("please specify one model format (%s)", s.UserStrsOr(vals))
```
Comment (deliahu) [inline pkg/operator/api/userconfig/errors.go]: nit: "please specify one model format" -> "please specify a model format"

File: pkg/operator/operator.go [hunk 16]
```diff
@@ -35,7 +35,6 @@ const operatorPortStr = "8888"
 
 func main() {
 	if err := config.Init(); err != nil {
-		config.Telemetry.ReportErrorBlocking(err)
```
Comment (deliahu) [inline pkg/operator/operator.go]: Is this intentional?

File: pkg/workloads/cortex/client/cortex/client.py [hunk 17]
```diff
@@ -81,13 +81,17 @@ def deploy(
         api_working_dir = os.path.join(working_dir, api_name)
         pathlib.Path(api_working_dir).mkdir(parents=True, exist_ok=True)
 
-        api_config = {"kind": "api", "model": model_path, "name": api_name}
+        api_config = {"kind": "api", "name": api_name}
 
-        if tf_serving_key is not None:
-            api_config["tf_serving_key"] = tf_serving_key
+        if model_format != "tensorflow" or model_format != "onnx":
```
Comment (deliahu) [inline pkg/workloads/cortex/client/cortex/client.py]: should this be `and`?

File: pkg/workloads/cortex/client/cortex/client.py [hunk 18]
```diff
@@ -68,9 +68,9 @@ def deploy(
             deployment_name (string): deployment name
             api_name (string): API name
             model_path (string): S3 path to an exported model
+            model_format (string): model format, must be "tensorflow" or "onnx" (default: "onnx" if model path ends with .onnx, "tensorflow" if model path ends with .zip or is a directory)
```
Comment (deliahu) [inline pkg/workloads/cortex/client/cortex/client.py]: do we still default based on the path? If not we could add the defaulting code here, or remove the default note

File: pkg/workloads/cortex/python_serve/api.py [hunk 19]
```diff
@@ -0,0 +1,156 @@
...
+    try:
+        ctx = Context(s3_path=args.context, cache_dir=args.cache_dir, workload_id=args.workload_id)
+        api = ctx.apis_id_map[args.api]
+        local_cache["api"] = api
+        local_cache["ctx"] = ctx
+
+        if api.get("python") is None:
+            raise CortexException(api["name"], "python key not configured")
+
+        if api["python"].get("inference") is not None:
```
Comment (deliahu) [inline pkg/workloads/cortex/python_serve/api.py]: Is this required?

File: docs/deployments/apis.md [hunk 20]
```diff
@@ -1,16 +1,37 @@
...
+
+
+## Inference
+Model initialization and other setup such as downloading vocabulary or initializing a tokenizer can be defined in the `init` function. The `predict` function is responsible for making an inference on a request and returning a prediction. The preprocessing of a request and postprocessing of model output can be done in the predict function.
+
+```python
+import ...
+
+def init(metadata):
+  # run more initializations here that may require metadata that you define in your yaml
```
Comment (deliahu) [inline docs/deployments/apis.md]: Does this "more" refer to global initializations? Should we add a comment above illustrating that?

File: docs/deployments/apis.md [hunk 21]
```diff
@@ -1,16 +1,37 @@
...
+Deploy your model as an API at scale. 
+
+A python interface below can be implemented to deploy most models with Cortex. Specify a python `inference` file that describes how to load your model and use it to make predictions. Cortex uses the `inference` file to deploy multiple replicas that can serve your model as an API. Deployment parameters such as minimum replica count, maximum replica count, enabling prediction monitoring can be configured using yaml.
+
+Besides providing a python interface, Cortex can serve the following exported model formats:
+- [TensorFlow saved model](./tensorflow/api.md)
+- [ONNX](./onnx/api.md)
+
+
+## Inference
```
Comment (deliahu) [inline docs/deployments/apis.md]: Since we link to `inference.md`, how do you feel about removing this info here?

File: docs/deployments/deployments.md [hunk 22]
```diff
@@ -7,6 +7,7 @@ Deployments are used to group a set of resources that can be deployed as a singl
 ```yaml
 - kind: deployment
   name: <string>  # deployment name (required)
+  python_root: <string>  # path to the root of your python folder that will be appended to PYTHONPATH
```
Comment (deliahu) [inline docs/deployments/deployments.md]: I added "(optional)" here. Do you think that makes sense, or would something like "(default: directory containing cortex.yaml)" make more sense?

File: docs/summary.md [hunk 23]
```diff
@@ -13,6 +13,7 @@
 * [Deployments](deployments/deployments.md)
 * [APIs](deployments/apis.md)
 * [Packaging models](deployments/packaging-models.md)
+* [Inference](deployments/inference.md)
```
Comment (deliahu) [inline docs/summary.md]: Should the other new files be added here?

File: examples/iris-classifier-pytorch/src/handler.py [hunk 24]
```diff
@@ -0,0 +1,31 @@
...
+                sample["sepal_width"],
+                sample["petal_length"],
+                sample["petal_width"],
+            ]
+        ]
+    )
+
+    output = model(input_tensor)
+    return labels[torch.argmax(output[0])]
+
```
Comment (deliahu) [inline examples/iris-classifier-pytorch/src/handler.py]: nit: extra new line
