### PR TITLE
Check EKS status before spinning up cluster

### LINKED ISSUE #556: While cluster is deleting, cortex cluster install reports that cluster is running
### Description

`cortex cluster delete` followed with `cortex cluster up` shortly after results in this error message:

```
error: Cortex does not currently support changing the instance type of a running cluster; please run `cortex cluster down` followed by `cortex cluster up` to create a new cluster
```

The error message should be something like:

```
error: Your cluster is currently deleting, please wait a few minutes and try again
```

### PR DESCRIPTION
**Pull request by deliahu**
Closes #556

---
Checklist:
- [ ] Run `make test` and `make lint`
- [ ] Test end to end manually (e.g. build/push all images, restart operator, and run `cx refresh`)
- [ ] Merge to master
- [ ] Delete the branch once it's merged

### CODE REVIEW

File: manager/install.sh [hunk 1]
```diff
@@ -31,6 +36,27 @@ function ensure_eks() {
     return
   fi
 
+  if [ "$cluster_status" == "DELETING" ]; then
+    echo "error: your Cortex cluster named $CORTEX_CLUSTER_NAME in $CORTEX_REGION is currently spinning down; please try again once it is compeletely deleted (may take a few minutes)"
```
Comment (vishalbollu) [inline manager/install.sh]: compeletely -> completely
