### PR TITLE
Unzip project to check if file exists and add request_handler file ha…

### LINKED ISSUE #427: API doesn't get updated if the request handler path is changed
### To Reproduce

1. deploy an api with a request handler configured
2. modify the request handler path and redeploy, you will be replied `deployment is up-to-date`

### LINKED ISSUE #428: Detect missing request handler before deploy API
### Motivation

Detect missing/incorrect request handler before deploying an API to make debugging faster and prevent unnecessary rolling updates.

### PR DESCRIPTION
**Pull request by vishalbollu**
…sh to api hash calculation

Closes #428, Closes #427 

---
Checklist:
- [ ] Run `make test` and `make lint`
- [ ] Test end to end manually (e.g. build/push all images, restart operator, and run `cx refresh`)
- [ ] Update examples
- [ ] Update documentation (add any new files to `summary.md`)
- [ ] Merge to master
- [ ] Cherry-pick into release branches if it's a bugfix
- [ ] Check [gitbook](https://docs.cortex.dev/v/master/) that docs look good and links function properly
- [ ] Alert team if dev environment changed
- [ ] Delete the branch once it's merged

### CODE REVIEW

File: pkg/operator/context/apis.go [hunk 1]
```diff
@@ -36,9 +37,18 @@ func getAPIs(config *userconfig.Config, deploymentVersion string, projectID stri
 		buf.WriteString(s.Obj(apiConfig.Tracker))
 		buf.WriteString(apiConfig.ModelFormat.String())
 		buf.WriteString(deploymentVersion)
-		buf.WriteString(projectID)
 		buf.WriteString(strings.TrimSuffix(apiConfig.Model, "/"))
 
+		if apiConfig.RequestHandler != nil {
+			buf.WriteString(projectID)
+
+			fileBytes, ok := projectFiles[*apiConfig.RequestHandler]
```
Comment (deliahu) [inline pkg/operator/context/apis.go]: as discussed, see if we can move this to userconfig package

File: pkg/operator/api/userconfig/apis.go [hunk 2]
```diff
@@ -269,6 +269,13 @@ func (api *API) Validate() error {
 		return errors.Wrap(ErrorTFServingOptionsForTFOnly(api.ModelFormat), Identify(api))
 	}
 
+	if api.RequestHandler != nil {
+		fmt.Println(projectFileMap[*api.RequestHandler])
```
Comment (deliahu) [inline pkg/operator/api/userconfig/apis.go]: Extra println?

File: pkg/operator/endpoints/deploy.go [hunk 3]
```diff
@@ -47,15 +47,21 @@ func Deploy(w http.ResponseWriter, r *http.Request) {
...
+	}
+
+	userconf, err := userconfig.New("cortex.yaml", configBytes)
 	if err != nil {
 		RespondError(w, err)
 		return
 	}
 
-	projectBytes, err := files.ReadReqFile(r, "project.zip")
+	err = userconf.Validate(projectBytes)
```
Comment (deliahu) [inline pkg/operator/endpoints/deploy.go]: I like how you split this out! Makes much more sense than the bool param to `New()`
