### PR TITLE
Log error only if k8s job is failed

### LINKED ISSUE #1822: Error log appears in aggregate logs (CloudWatch/StackDriver) when job is not failed
#### Description

```text
{
  "level": "error",
  "ts": 1611322061.064799,
  "caller": "batchapi/cron.go:379",
  "message": "at least one worker had status Succeeded and terminated for reason completed (exit_code=0)",
  "labels": {
    "apiKind": "BatchAPI",
    "apiName": "image-classifier",
    "jobID": "69a36f366c2f5d92"
  },
  "stacktrace": "github.com/cortexlabs/cortex/pkg/operator/resources/job/batchapi.checkForJobFailure \n\t/home/miguelvr/cortex/pkg/operator/resources/job/batchapi/cron.go:379\ngithub.com/cortexlabs/cortex/pkg/operator/resources/job/batchapi.checkIfJobCompleted\n\t/home/miguelvr/cortex/pkg/operator/resources/job/batchapi/cron.go:287\ngithub.com/cortexlabs/cortex/pkg/operator/resources/job/batchapi.ManageJobResources\n\t/home/miguelvr/cortex/pkg/operator/resources/job/batchapi/cron.go:192\ngithub.com/cortexlabs/cortex/pkg/lib/cron.Run.func1\n\t/home/miguelvr/cortex/pkg/lib/cron/cron.go:36\ngithub.com/cortexlabs/cortex/pkg/lib/cron.Run.func2\n\t/home/miguelvr/cortex/pkg/lib/cron/cron.go:52"
}
```

### PR DESCRIPTION
**Pull request by RobertLucian**
Fixes #1822

---

checklist:

- [x] run `make test` and `make lint`
- [ ] test manually (i.e. build/push all images, restart operator, and re-deploy APIs)

### CODE REVIEW

**Review by miguelvr — APPROVED** [review]
LGTM

File: pkg/operator/resources/job/batchapi/cron.go [hunk 1]
```diff
@@ -366,18 +366,24 @@ func checkForJobFailure(jobKey spec.JobKey, k8sJob *kbatch.Job) (bool, error) {
...
-				reason := strings.ToLower(containerStatus.State.Terminated.Reason)
-				jobLogger.Errorf("at least one worker had status %s and terminated for reason %s (exit_code=%d)", string(podStatus), reason, exitCode)
-				reasonFound = true
+		if k8sJob != nil && int(k8sJob.Status.Failed) > 0 {
+			podStatus := k8s.GetPodStatus(&pod)
+			for _, containerStatus := range pod.Status.ContainerStatuses {
+				if containerStatus.LastTerminationState.Terminated != nil {
+					exitCode := containerStatus.LastTerminationState.Terminated.ExitCode
+					reason := containerStatus.LastTerminationState.Terminated.Reason
+					if k8s.ReasonCompleted != reason {
```
Comment (deliahu) [inline pkg/operator/resources/job/batchapi/cron.go:375]: nit `reason != k8s.ReasonCompleted` (also below)

Comment (deliahu) [inline pkg/operator/resources/job/batchapi/cron.go:375]: consider: `if k8s.ReasonCompleted != reason || exitCode != 0 {`

**Review by deliahu — APPROVED** [review]
