### PR TITLE
Download model with init containers

### LINKED ISSUE #301: Use init container to download TensorFlow model
### Description

For TensorFlow, the `api` container in the serving pod is responsible for downloading the model. Because the TF Serving container starts at the same time, until the model is downloaded and unzipped, TF Serving shows error messages like this:

```
E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path /mnt/model for servable default
```

and/or like this:

```
E tensorflow_serving/util/retrier.cc:37] Loading servable: {name: default version: 42} failed: Not found: Specified file path does not appear to contain a:
- Session bundle (should have a file called `export.meta`)
- or, SavedModel bundle (should have a file called `saved_model.pb`)
Specified file path: /mnt/model/42
```

This is working as expected (eventually the model will be downloaded and loaded by TF Serving), but could be confusing to the user as to why there are error logs.

### Fix

Use an init container to download the model before starting the `api` or `serve` containers

### PR DESCRIPTION
**Pull request by 1vn**
Closes #301

---
Checklist:
- [ ] Run `make test` and `make lint`
- [ ] Test end to end manually (e.g. build/push all images, restart operator, and run `cx refresh`)
- [ ] Update examples
- [ ] Update documentation (add any new files to `summary.md`)
- [ ] Merge to master
- [ ] Cherry-pick into release branches if it's a bugfix
- [ ] Check [gitbook](https://docs.cortex.dev/v/master/) that docs look good and links function properly
- [ ] Alert team if dev environment changed
- [ ] Delete the branch once it's merged

### CODE REVIEW

File: pkg/operator/workloads/api_workload.go [hunk 1]
```diff
@@ -275,9 +275,29 @@ func tfAPISpec(
 				"userFacing":   "true",
 			},
 			Annotations: map[string]string{
-				"sidecar.istio.io/inject": "true",
```
Comment (deliahu) [inline pkg/operator/workloads/api_workload.go]: Is this necessary?

File: pkg/operator/workloads/api_workload.go [hunk 2]
```diff
@@ -275,9 +275,29 @@ func tfAPISpec(
...
+				"traffic.sidecar.istio.io/excludeOutboundIPRanges": "0.0.0.0/0",
```
Comment (deliahu) [inline pkg/operator/workloads/api_workload.go]: Reading through the [docs](https://istio.io/docs/setup/kubernetes/additional-setup/cni/#traffic-redirection-parameters) on this again, this annotation might not be necessary. Can you try without and see if it works?
